### ISSUE TITLE
Allow registering the fallback consumer to read response

### ISSUE THREAD

**Issue by elakito** [go-openapi/runtime#104]
Currently, if the content-type of the response doesn't match those registered consumers, the response is simply rejected with the error.
  no consumer: ...

I would like to have an option of reading the response in this case and I would like to ask if we can treat the consumer registered for "*/*" to be used as the fallback consumer.

I have created a commit that shows the proposed change``
https://github.com/elakito/runtime/commit/e7607f129dafe0480dced674cf6830c763873b68

Could you comment on this proposal?

regards, aki

**Comment by casualjim** [comment]
I think this change looks reasonable

**Comment by elakito** [comment]
created the above PR.
thanks
