### ISSUE TITLE
use context instead of "golang.org/x/net/context"

### ISSUE THREAD

**Issue by etsangsplk** [go-openapi/runtime#112]
quick grep shows: 
./vendor/github.com/go-openapi/runtime/client_operation.go:20:	"golang.org/x/net/context"
./vendor/github.com/go-openapi/runtime/.travis.yml:12:- go get -u golang.org/x/net/context
./vendor/github.com/go-openapi/runtime/client/runtime.go:33:	"golang.org/x/net/context"

**Comment by fredbi** [comment]
Closed by #113
