### ISSUE TITLE
Unify the logging format when debugging is enabled

### ISSUE THREAD

**Issue by hectorj2f** [go-openapi/runtime#118]
When we enable the debug mode, it uses the logging format defined in the standardLogger (https://github.com/go-openapi/runtime/blob/master/middleware/context.go#L35). It'd be great to reuse the Logger defined when configuring the runtime.

Is it possible to unify the logger format when debug is enabled? Or I am missing something

**Comment by fredbi** [comment]
The runtime with an injectable Logger is for constructing a client.

On the server side, logging is scattered among different components so it's more difficult.
