### ISSUE TITLE
Client timeout of 0 causes immediate "context deadline exceeded"

### ISSUE THREAD

**Issue by timbunce** [go-openapi/runtime#126]
This is arguably a duplicate of #14 which pointed out a doc deficiency and was addressed by telling the user to use operations.New*Params() functions.

It's also arguably a duplicate of go-swagger/go-swagger#919 where somebody else stumbled into the same problem. @casualjim responded that "We need a way to express forever because there are certain cases where you really don't want a request to timeout.", "... you want the connection to be opened forever, forever is signaled by using 0" and the case was closed.

Unless I'm misunderstanding something that seems to be a mistake as [the code](https://github.com/go-openapi/runtime/blob/4559f9fe8183f36685514029366d833e3a960292/client/runtime.go#L367-L384) doesn't operate that way.

I think the `hasTimeout` var should only be set true if `request.timeout` is non-zero.

**Comment by said-saifi** [comment]
Does the suggested solution have any drawbacks? As the current code also causes an issue where the timeout is not respected. So if you have both context set and timeout parameter set then the timeout will just be ignored. For example:

```go
// let's assume that we have a ctx defined before that did not have a deadline

params := NewAddOneParamsWithContext(ctx)
params.SetTimeout(10*time.Second)

// calling AddOne which will then call Submit function
c.AddOne(params, ...) 
```

The existing code will not respect the timeout as the context is set. 

A workaround is to pass the timeout in the context, so you can instead do:
```go
// let's assume that we have a ctx defined before that did not have a deadline

ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
defer cancel()

params := NewAddOneParamsWithContext(ctx)

// calling AddOne which will then call Submit function
c.AddOne(params, ...) 
```

So I'm checking if there is any drawbacks of refactoring the code to something like:
```go
var pctx context.Context
switch {
case operation.Context != nil:
    pctx = operation.Context
case r.Context != nil:
    pctx = r.Context
default:
    pctx = context.Background()
}

var ctx context.Context
var cancel context.CancelFunc
if request.timeout != 0 {
    ctx, cancel = context.WithTimeout(pctx, request.timeout)
} else {
    ctx, cancel = context.WithCancel(pctx)
}
defer cancel()
```

**Comment by youyuanwu** [comment]
"Possible solution 1" above is ok. "Possible solution 2" is not standard of how to handle ctx in Go.
