### ISSUE TITLE
client timeout is 0

### ISSUE THREAD

**Issue by tompscanlan** [go-openapi/runtime#14]
I was getting the error "context deadline exceeded" using a generated client.  After some debugging, I discovered the default timeout is not affecting the call to Submit() in  `client/runtime.go`.

request.timeout is 0 in this line:

    ctx, cancel := context.WithTimeout(pctx, request.timeout)

Setting a good timeout just before that line gets me past the error.

    request.SetTimeout(30 * time.Second)
    ctx, cancel := context.WithTimeout(pctx, request.timeout)

Am I just using the client wrong, or is this a bug?

**Comment by tompscanlan** [comment]
I think it may be a documentation bug.  Docs say to try:

    transport := httptransport.New(os.Getenv("TODOLIST_HOST"), "", nil)
    client := apiclient.New(transport, strfmt.Default)
    resp, err := client.Operations.All(operations.AllParams{})

But to set a timeout, you can call something like:

    transport := httptransport.New(os.Getenv("TODOLIST_HOST"), "", nil)
    client := apiclient.New(transport, strfmt.Default)
    resp, err := client.Operations.All(operations.NewAllParamsWithTimeout(30 * time.Second))

That also gets me around the bug.  Not sure why the default timeout isn't being honored, but this works for me.

**Comment by casualjim** [comment]
right, and if you use operations.NewAllParams() it should already default to 30 seconds

**Comment by tompscanlan** [comment]
I'm the bug... ;(
