### ISSUE TITLE
Empty req.Host in client runtime

### ISSUE THREAD

**Issue by vearutop** [go-openapi/runtime#145]
Some time ago Opencensus library switched to use `req.Host` instead of `req.URL.Host` with https://github.com/census-instrumentation/opencensus-go/pull/1036.

But runtime does not fill `req.Host`:
https://github.com/go-openapi/runtime/blob/v0.19.2/client/runtime.go#L352

Because of that new versions of Opencensus started producing metrics with `http_client_host=""` which is unfortunate.

Please fill `req.Host` value too.

**Comment by fredbi** [comment]
duplicates #143

**Comment by vearutop** [comment]
Hopefully this issue can be resolved quickly given the two PRs. :)
