### ISSUE TITLE
runtime-validate circular dependency

### ISSUE THREAD

**Issue by serge-v** [go-openapi/runtime#150]
runtime-v0.19.3 depends on validate-v0.19.2
validate-v0.19.2 depends on runtime-v0.19.0

references:
https://github.com/go-openapi/runtime/blob/v0.19.3/go.mod
https://github.com/go-openapi/validate/blob/v0.19.2/go.mod

**Comment by serge-v** [comment]
deps chart:
![deps](https://user-images.githubusercontent.com/4163168/61790904-78116500-ade6-11e9-8257-0bc440016957.png)

**Comment by casualjim** [comment]
Yes but one is a test dependency. Just use the replace to the 0.19.3

**Comment by serge-v** [comment]
also go mod vendor selects the highest version, so no problem here. Thanks.
