### ISSUE TITLE
Allow access to the PathPattern given a MatchedRoute

### ISSUE THREAD

**Issue by wlmaguire** [go-openapi/runtime#152]
We would like to get access to the path pattern from the handlers.  We can get the MatchedRoute from the context, but from that route are unable to see the private routeEntry.

Please add the following to runtime/middleware/router.go

// PathPattern returns the path pattern for the matched route
func (m *MatchedRoute) PathPattern() string {
	return m.routeEntry.PathPattern
}

**Comment by casualjim** [comment]
the `PathPattern` property is an exported property. You can just access it from the MatchedRoute.

This works anywhere: 
```
ri, req, err := api.Context(req).RouteInfo(nil)
// ... do more stuff, like handle error ...
ri.PathPattern
```

you do need to get a hold of the api object which you have access to in the configure_xxx.go file. For example in the todo-list example that's this object: https://github.com/go-swagger/go-swagger/blob/master/examples/todo-list/restapi/operations/todo_list_api.go
