### ISSUE TITLE
v0.19.10 is introducing an incompatible minor change, that breaks liveness/readiness probes

### ISSUE THREAD

**Issue by v-antech** [go-openapi/runtime#174]
Release v0.19.10 broke our kubernetes liveness/readiness probes. Now they return 406 instead of a 200 when the server boots up.

I suspect line `307` in `context.go` from this commit: 654e3936f213b9f44cc98367040a4620031ebb1b

This requires the Accept request type to be explicitly provided and also the produces type to be explicitly defined for empty GET requests (used in kubernetes liveness/readiness probes).

**Comment by casualjim** [comment]
```go get -u github.com/go-openapi/runtime@v0.19.13```

**Comment by v-antech** [comment]
Awesome, that does the trick, thanks!
