### ISSUE TITLE
can application/zip mimetype be added to go-openapi/runtime?

### ISSUE THREAD

**Issue by RubenGarcia** [go-openapi/runtime#179]

**Comment by fredbi** [comment]
The client runtime comes preconfigured with a few common Consumers/Producers.

It might be a nice addition to add a zipped version of the ByteStream consumer/producer, but it is not there yet.
But you may add your own.

The client runtime is fully configurable to add custom ones following the same interface. There: 
https://github.com/go-openapi/runtime/blob/442694d245b6822df8701f363b33b85bc483b5b1/client/runtime.go#L228

On the server side, the middleware.RoutableAPI sets map of Consumers/Producers for mime types in a similar way.
You may see here how this is used for generated APIs:
 https://github.com/go-swagger/go-swagger/blob/dfab389b1494c6a13a9d6f06fa65e846edf62e1a/examples/task-tracker/restapi/operations/task_tracker_api.go#L426


The other use case is with an untyped API.  You may register custom Consumers/Producers like so:
 https://github.com/go-openapi/runtime/blob/442694d245b6822df8701f363b33b85bc483b5b1/middleware/untyped/api.go#L116

**Comment by RubenGarcia** [comment]
Thank you.
