### ISSUE TITLE
RESTCONF edge case in denco

### ISSUE THREAD

**Issue by boisjacques** [go-openapi/runtime#182]
OpenAPI files for RESTCONF generated from YANG modules have an edge case that is not caught with the current denco implementation. Paths with path parameters are generated like this: `/path/to/key=:value` since path parameters in RFC 8040 are defined as key-value pair connected by an equals sign.

**Comment by casualjim** [comment]
I assume `key=:value` should be treated as opaque value right? And the issue here is that denco thinks :value is a path parameter?

**Comment by boisjacques** [comment]
The issue is, that denco does not recognise that `:value` is a parameter at all since it is not preceded by a `/` but rather by a `=`

There is PR #183 that fixes that by adding a new RESTCONF delim.

**Comment by casualjim** [comment]
https://github.com/go-openapi/runtime/releases/tag/v0.19.21
