### ISSUE TITLE
DEBUG mode should not dump response body when response body is non-text

### ISSUE THREAD

**Issue by yabberyabber** [go-openapi/runtime#193]
I find DEBUG mode super helpful when my client doesn't get what it expects from the server. However, much of my application involves shoveling binary content back and forth between servers. When the response body is a binary blob, DEBUG mode throws gibberish into my terminal and sometimes messes it up.

I would like to fix DEBUG mode so that, when the media type is a known non-text format, the DEBUG mode only prints the response headers, not the response body.

Grepping around, it looks like this https://github.com/go-openapi/runtime/blob/master/client/runtime.go#L454 is the code that needs to change. 

If this seems like a reasonable feature request, I'm happy to post a patch.

**Comment by fredbi** [comment]
We have this for responses: 4243b2d8d910441ac79adc8654cf3ac42fc62fc0
The code pointed to by the OP relates to requests

**Comment by fredbi** [comment]
This issue has been resolved with  https://github.com/go-openapi/runtime/commit/4243b2d8d910441ac79adc8654cf3ac42fc62fc0
