### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by fjvierap** [go-openapi/runtime#202]
Hi, is there planned to create some tag with latest from master?. We would like to use latest contributions as go module. Thanks

**Comment by kzys** [comment]
Thanks both! Regarding analysis, the last commit somehow added `loads` package again. Could you take a look https://github.com/go-openapi/analysis/pull/78?

**Comment by casualjim** [comment]
I just merged and tagged as v0.21.1 for  analysis

**Comment by kzys** [comment]
How about releasing validate? After that, I can upgrade go.mod below.

https://github.com/go-openapi/runtime/blob/6bf365991ddb89a5f3c7dccf4ffb16c464909848/go.mod#L11

**Comment by kzys** [comment]
Thanks! I've opened #234.

**Comment by casualjim** [comment]
merged and tagged v0.23.1
