### ISSUE TITLE
client.request.buildHTTP overwrites query parameters passed in the base path

### ISSUE THREAD

**Issue by jsilland** [go-openapi/runtime#207]
When calling `client.request.buildHTTP` with a `basePath` which contains query parameters (e.g. `/path?foo=bar`), those parameters are erased from the resulting HTTP request. This is happening because the `RawQuery` field in the url is replaced with the encoded params after the `urlPath` is used to construct the URL: 

https://github.com/go-openapi/runtime/blob/60c8ebd1b65257ddca4a08a0348f2141099863a2/client/request.go#L289-L294

I would like to propose that this method merges the respective `url.Values` instead of doing a straight replacement of the raw query. Happy to contribute a repro and a patch if the maintainers agree on the path forward.

The use case I'm trying to support is the Flickr API, which is not RESTful in nature. Instead, there is a single endpoint and method names are passed as parameters — they do [publish a Swagger spec](https://github.com/flickr/flickr-api-swagger/blob/60354fa7f345f9638369d91a9f5c2e090e6f3a12/dist/schema.json#L20-L24
) which uses a trick where the specified paths embed the method name themselves. This allows telling apart methods from one another, since the paths are all distinct:

```json
  "paths": {
    "/rest?method=flickr.favorites.getList": {
      "get": {
        "operationId": "getFavoritesByPersonID",
        "description": "Returns a list of the user's favorite photos. Only photos which the calling user has permission to see are returned.",
```

As it stands, this issue precludes from using this spec with this OpenAPI runtime.

**Comment by jsilland** [comment]
The effort was pretty low, so I've worked on a repro and proposed fix, which I've pushed at https://github.com/jsilland/runtime/tree/julien/207

**Comment by youyuanwu** [comment]
Not sure if "/rest?method=flickr.favorites.getList" will pass swagger validation.

I think there is no harm supporting this in runtime.

@casualjim what do you think?

**Comment by casualjim** [comment]
yeah please send a PR

**Comment by jsilland** [comment]
PR open at https://github.com/go-openapi/runtime/pull/209

**Comment by RubenGarcia** [comment]
Since this is merged, can you confirm all is good and close this?

**Comment by jsilland** [comment]
Yes, this is now working as intended in my project — thanks for the review!
