### ISSUE TITLE
Bytestream ConsumerFunc does not support *string as data interface {}

### ISSUE THREAD

**Issue by RubenGarcia** [go-openapi/runtime#225]
The following error is produced:
```
parsing body body from "" failed, because 0xc0005c4490 (*string) is not supported by the 
ByteStreamConsumer, can be resolved by supporting Writer/BinaryUnmarshaler interface
```
This is an issue because go-swagger and stratoscale generate the following code:
```
var body string
if err := route.Consumer.Consume(r.Body, &body); err != nil
```

**Comment by youyuanwu** [comment]
I added string for Producer: https://github.com/go-openapi/runtime/blob/0e1252fe7186ce425500314269d82ad4613f017e/bytestream.go#L132

For consumer it should be easy to add too. What example spec produces this code?

**Comment by RubenGarcia** [comment]
Here are the relevant lines in the swagger definition:
```
    patch:
      consumes:
        - application/offset+octet-stream
      parameters:
        - in: body
          name: Body
          schema:
            type: string
      responses:
        '204':
          description: Upload offset was updated
```

**Comment by RubenGarcia** [comment]
I'll add the change to the Consumer.

**Comment by RubenGarcia** [comment]
We can close issue after patch was merged.
