### ISSUE TITLE
ReDoc uses unmodifiable spec path

### ISSUE THREAD

**Issue by andrewpmartinez** [go-openapi/runtime#226]
It appears that when ReDoc is used, the OpenAPI 2.0/Swagger spec is defaulted to "/swagger.json" and ignores `basePath` while also providing no way to directly or indirectly set `.SpecURL` in the Redoc template.

In my situation, I'm hosting multiple separate APIs from the same listener. I can load Redoc from `myhost/api-type/api-sub-type/version/docs` but the rendered template always points to `myhost/swagger.json`.

I could not find a way to provide an override, alter the value directly, or make the `basePath` from my OpenApi 2.0 spec be referenced in any way.

Changes to `runtime` appear to be:
- alter `RedocOpts` field `SpecURL` to be a relative path: "./swagger.json" or "swagger.json" instead of "/swagger.json"
- alter `RedocOpts` field `SpecURL` to take `BasePath` into account
- provide a way to override/set the SpecURL externally from `Context`

If there is a different way to handle this or I am missing something please let me know!

**Comment by andrewpmartinez** [comment]
This still seems to be an issue.

**Comment by fredbi** [comment]
Studying this issue report,  I gather that:
1. When used independenctly, the Redoc middleware is configurable as far as SpecURL is concerned.
   * BasePath and Path tell this middleware how to serve the UI asset, SpecURL tells where to find the spec document
   * SpecURL, BasePath and Path are unrelated parameters
2. When used independently, the Spec middleware is configurable as far as the path is concerned.
   * the document name "swagger.json" is hard-coded
3.  When using the fully assembled API middleware stack exposed by Context, the spec document is served at "/swagger.json",  the UI (redoc) is served at "{API base path}/docs". These are not currently configurable.
