### ISSUE TITLE
Is there anyway to create a default header?

### ISSUE THREAD

**Issue by Sczlog** [go-openapi/runtime#235]
It seems like we can only set header by request,
How to add a default header for each request?

**Comment by casualjim** [comment]
You can use a plain net/http middleware for that. You can register them globally or per operation

https://goswagger.io/use/middleware.html

**Comment by Sczlog** [comment]
@casualjim, thanks for reply, but I am working on generating a client. The doc seems like using middleware for server not client.

**Comment by casualjim** [comment]
On the client you can use a Transport and wrap the default one. 

https://github.com/go-openapi/runtime/blob/master/client/runtime.go#L226

**Comment by Sczlog** [comment]
@casualjim thanks
