### ISSUE TITLE
Authorization token

### ISSUE THREAD

**Issue by ionik-dev** [go-openapi/runtime#236]
Hi all.

I have met with not clear logic or bug with setting auth token for generated client.

As for my code i set default token via:

```go
....
import (
    "github.com/go-openapi/runtime/client"

    "github.com/myproject/internal/generated/clients/myextservice/client/orders"
)
....
func NewClient(host, basePath, scheme, token string) {
....
    t := client.New(host, basePath, []string{scheme})
    t.DefaultAuthentication = client.BearerToken(token)
....
}
```

Than later in specific client method for external api endpoint i need to set a different token(business logic of external service) and do this via:
```go
func (c *Client) CreateOrder(ctx context.Context, token string) {
....
    params := orders.
        NewCreateOrderParamsWithContext(ctx).
        WithBody(body).
        WithAuthorization(token)

    resp, err := c.client.Orders.CreateOrder(params)
....
}
```
As for debug info request was sending with default token and no overwrite was made by passing params struct with new token(assigned by `WithAuthorization(token)`)  to `CreateOrder(params)` method

Also found this code in **github.com/go-openapi/runtime/client/runtime.go** for Submit method (line 363)
Seems that we try to get token value from `operation.AuthInfo` field which is nil but not from params value with assigned token and than later use a default token if set
![image](https://user-images.githubusercontent.com/4531254/158125737-6f9f61f2-3dd9-418e-81dd-28968554f3b0.png)

Expected behavior:

- `WithAuthorization(token)` overwrites the default client token, assigned on it's creation

**Comment by casualjim** [comment]
I think this client was not generated with a principal, which is why you don't see the ability to pass in an auth info writer. 
something like this: 

```sh
swagger generate client -A YourApp -f ./swagger.yml -P 'models.YourUserObject' 
```

I've added the detection for an authorization header but it leaves query params and form values unaddressed.
