### ISSUE TITLE
Unable to set a parameter of type file as optional

### ISSUE THREAD

**Issue by MakarandNsd** [go-openapi/runtime#246]
I am not sure if no one needed this before, but I have a use case where the file type parameter is optional, but the code below returns error before validating whether the field is required.

https://github.com/go-openapi/runtime/blob/3f9800fb72fae00e99a99db505da3b330f847e8e/middleware/parameter.go#L206-L213

I can throw in an additional if condition to check if the file is optional and return nil. Please let me know if that works.

**Comment by casualjim** [comment]
yes please send a PR

**Comment by MakarandNsd** [comment]
@casualjim , please review the pr

**Comment by MakarandNsd** [comment]
added test cases at #248 
@casualjim
