### ISSUE TITLE
Long term plans for current OpenTracing implementation?

### ISSUE THREAD

**Issue by josephwoodward** [go-openapi/runtime#249]
Whilst looking at options for tracing egress traffic within services I noticed go-openapi currently supports OpenTracing via its [`WithOpenTracing` extension](https://github.com/go-openapi/runtime/blob/219a7455b4441979f14df833e965bc521d289ccf/client/runtime.go#L296-L300). Given OpenTracing has since been archived (and the [SDK deprecated](https://github.com/opentracing/opentracing-go)) and become part of OpenTelemetry I'm interested to know the future plans for this API within go-openapi and whether you'll eventually look at migrating to OpenTelemetry?

**Comment by josephwoodward** [comment]
Would you be open to a PR to introduce a `WithTracing` extension that adds OpenTelemetry support? We could then look at eventually retiring the `WithOpenTracing` extension in a future release.

**Comment by casualjim** [comment]
all prs are welcome

**Comment by josephwoodward** [comment]
@casualjim I've started work on this in https://github.com/go-openapi/runtime/pull/254

**Comment by josephwoodward** [comment]
@casualjim I think the pull request is pretty much ready for review now. There are a few additional test cases I'd like to add but the bulk of the implementation is ready whenever you have the time.

**Comment by josephwoodward** [comment]
Now that #254 has been merged it feels like this can be closed.
