### ISSUE TITLE
Feature Request: Use semantic versioning

### ISSUE THREAD

**Issue by ryanwalls** [go-openapi/runtime#25]
I've run into dependency mismatches between go-openapi repos.  It would be easier to avoid mismatches if they used semantic versioning.

**Comment by bcomnes** [comment]
fwiw go modules + the v0.18.0 tag has been very reliable so far. But yes! a big 👍 on this one.

**Comment by casualjim** [comment]
But they use semantic versioning now, unless I misunderstand the requirement

**Comment by bcomnes** [comment]
Thats what it seemed like, I would say this is good to close now.
