### ISSUE TITLE
How to disable `try it out` option for the swagger-ui

### ISSUE THREAD

**Issue by sheikhasim** [go-openapi/runtime#318]
I'm using the `middleware.SwaggerUI` to serve openapi spec over the swaggerUI. I want to disable the try it out option for all endpoints.
Is there a way to do that ?

**Comment by fredbi** [comment]
There are a few options to the UI templates.
If this option is configurable in the JS asset, you can provide your own template with this setting using the `middleware.WithUITemplate({template string})` option.

The default template that configures the UI widget is there: https://github.com/go-openapi/runtime/blob/5a6846cd279829a24dd000c1648e6ba9b5356787/middleware/swaggerui.go#L112
