### ISSUE TITLE
Path not found error : trailing slash url

### ISSUE THREAD

**Issue by alexmontecucco** [go-openapi/runtime#34]
## Problem statement

When I specify endpoints ending with a slash in my swagger file, at runtime when trying to reach the same endpoint I get a `{"code":404,"message":"path /trailingslashpath/ was not found"}` response.

It looks related to this: [github.com/go-swagger/go-swagger/pull/292](https://github.com/go-swagger/go-swagger/pull/292) but the problem does not come from the same code.

I don't know if this is an expected result or not.
The behavior is due to the [DefaultRouter](https://github.com/go-openapi/runtime/blob/master/middleware/router.go) function. It calls the 'path.Join' function which removes any trailing slash except for the root path. 
The result is that no handler seems to be registered.

**Comment by casualjim** [comment]
fixed by 196f81713650c99a470614414b1f12e7ecc2f5d3
