### ISSUE TITLE
Sending form data in 'chuncked' Transfer-Encoding

### ISSUE THREAD

**Issue by yan-zhuang** [go-openapi/runtime#39]
When constructing client request with form data, the request.BuildHTTP() does not set the content length before writing form data as the body. This causes that a chunked transfer is declared, and corrupts the form data.

**Comment by yan-zhuang** [comment]
Hi,
I have a fix ready. Would anyone please let me know about the process of submitting a fix?
Thanks,
Yan

**Comment by GlenDC** [comment]
Hi Thank you.

The process goes as follows:

- Create a branch that is prefixed with the issue number that you are fixing (39) in this case;
- Make sure that all unit-tests run, and also that you have added unit-tests, unless it is not possible;
- Push your branch with your commit;
- Make a pull request;
- Wait for review;

**Comment by yan-zhuang** [comment]
Thank you Glen.
I've done the step 1 and 2. The push failed with the permission error:
`$ git push --set-upstream origin 39
ERROR: Permission to go-openapi/runtime.git denied to yan-zhuang.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`
How do I get the permission?
Thanks,
Yan

**Comment by casualjim** [comment]
Check this out on creating a Pull Request

https://help.github.com/articles/creating-a-pull-request/
https://www.thinkful.com/learn/github-pull-request-tutorial/

**Comment by yan-zhuang** [comment]
@casualjim Thanks. But I didn't get what I need. I believe that I need to be able to push the branch to the remote repository in order to create a pull request.

**Comment by casualjim** [comment]
you fork this repository, then push to a branch of your fork.
When you're happy with that branch you submit a pull request to this repo.  If/when you submit PR's regularly I can add you as a comitter

**Comment by yan-zhuang** [comment]
@casualjim @GlenDC Thanks. The pull request has been created.
