### ISSUE TITLE
Are there any other reasons to use Gorilla context a part of the historical ones?

### ISSUE THREAD

**Issue by ifraixedes** [go-openapi/runtime#47]
I'm wondering why Gorilla context is used than the standard context package or the old `golang.org/x/net/context`.

I guess that these sources were created before the existence of the official context package, so the Gorilla context was a great solution, however are there any other reasons or I'm wrong in my guess?

Thanks!

**Comment by casualjim** [comment]
you're right just historical ones, it could be refactored to just use golang's context package

**Comment by ifraixedes** [comment]
I've started to do the swap, however I'm facing to have to change, at least, the signature of the function [`middleware/context.ContentType`](https://github.com/ifraixedes/go-openapi-runtime/blob/47-swap-gorilla-ctx/middleware/context.go#L307) because the request must change when a values is set to the context.

If the signature of such function change then it's a breaking change, because the function is exported, so I would like to know what you think about it and if you bear in mind other solution, because you have a bigger picture of the project than myself.

**Comment by casualjim** [comment]
I have no objection to changing that signature. We have to make sure it's mentioned in the release notes as a breaking change
