### ISSUE TITLE
[Question] How to extend/customize Authorization function?

### ISSUE THREAD

**Issue by etsangsplk** [go-openapi/runtime#51]
Example, OAuth uses scope for Authorization, which maps to the url path.
But it is on a resource route level. The values of the parameters are not looked at. E.g.
If the access control needs to say prevent user to execute the http handler but only when the parameter values are of values X or Y, I probably need a custom plugin written.
But it looks like the current framework only supports url route level, just wonder if there are anything I missed looking at.

**Comment by kenjones-cisco** [comment]
I'm looking at the same currently.

The changes required to include this would be the following:

- [ ] Create public interface for Authorizer (same concept as runtime.Authenticator)
- [ ] Add Authorizer to runtime/middleware/router.go (routeEntry) and set within AddRoute function
- [ ] Add call to Authorizer within runtime/middleware/context.go (Authorize)
- [ ] Update go-swagger to add configurable hook when securityDefinition defined, with an empty no-op implementation provided by default.

Initial thoughts on the interface:
// *http.Request required to access Method, Path, Headers, and Body
// interface{} represents the Principal (value returned from Authenticate)
// return error to indicate failure or nil if success
Authorize(*http.Request, interface{}) error

The Authorizer will only be called after successful response from Authenticator. If Authorizer returns error, HTTP Status 403 (StatusForbidden) will be returned.

@casualjim Any input/feedback before I start working on a PR?
