### ISSUE TITLE
Commit 0fd0aae5036b889b33df1d058572b8692ae97602 breaks backward compatibility

### ISSUE THREAD

**Issue by ferotap** [go-openapi/runtime#62]
After the above mentioned commit, go-swagger server code generations start to fail with error: *XyzAPI does not implement middleware.RoutableAPI (missing Authorizer method)

**Comment by reddec** [comment]
Confirm it

**Comment by casualjim** [comment]
build from go-swagger/go-swagger master and you should be good to go
