### ISSUE TITLE
Set* does not show up in request when called in ClientAuthInfoWriter

### ISSUE THREAD

**Issue by MStoykov** [go-openapi/runtime#78]
Because [most of the request is build before calling ClientAuthInfoWriter in buildHttp](https://github.com/go-openapi/runtime/blob/e14965b7171054b0716bb9c08d653ac7871517ea/client/request.go#L108) any changes to the query, body or path are not actually reflected in the final request that is sent.  Changes to headers appear to be okay :). 

As per the [Specification](https://swagger.io/docs/specification/authentication/api-keys/) at least query parameters should be changeable from inside ClietnAuthInfoWriter, as in [APIKeyAuth](https://github.com/go-openapi/runtime/blob/e14965b7171054b0716bb9c08d653ac7871517ea/client/auth_info.go#L40). 

Unfortunately  my tries at fixing produce way too much changes IMO and I still have not figured out if changing the body should be possible from inside ClientAuthInfoWriter and how to make everything in httpBuild work with it.

**Comment by MStoykov** [comment]
@casualjim May you look at this.
I don't like bumping my own issues but I need this to work and would prefer not to vendor it from my repo :)

**Comment by casualjim** [comment]
thanks for the bump
