### ISSUE TITLE
Runtime/client doesn't properly handle escaped path params

### ISSUE THREAD

**Issue by e-zhang** [go-openapi/runtime#84]
The runtime server path correctly unescapes any URL path params, but there currently seems to be a gap on the generated client side for escaping URL path params.

Parameters are not escaped before adding them to the URL in `buildHTTP`. 
As a stop gap, the caller of the client can path escape the path params when creating the generated Parameters object. However this also reveals a subtler issue with the `net/url` and `net/http` package in `go`.

Here's a minimal example to show what happens
```
func main() {
	pathParam := "needs/escape"
	escaped := url.PathEscape(pathParam)
	fmt.Println(escaped)
	p, e := url.Parse(escaped)
	if e != nil {
		fmt.Println(e)
		return
	}
	
	fmt.Println("URL Parse")
	fmt.Println(p.Path)
	fmt.Println(p.RawPath)
	fmt.Println(p.EscapedPath())
	
	p.Path = "basepath/" + p.Path
	
	fmt.Println("URL w/ modified Path")
	fmt.Println(p.Path)
	fmt.Println(p.RawPath)
	fmt.Println(p.EscapedPath())
	
	p.RawPath = "basepath/" + p.RawPath
	fmt.Println("URL w/ modified Path and RawPath")
	fmt.Println(p.Path)
	fmt.Println(p.RawPath)
	fmt.Println(p.EscapedPath())
}
```
The corresponding output is
```
needs%2Fescape
URL Parse
needs/escape
needs%2Fescape
needs%2Fescape
URL w/ modified Path
basepath/needs/escape
needs%2Fescape
basepath/needs/escape
URL w/ modified Path and RawPath
basepath/needs/escape
basepath/needs%2Fescape
basepath/needs%2Fescape
```

In https://github.com/go-openapi/runtime/blob/master/client/runtime.go#L260, only the `.Path` field of URL is modified, as a result, `EscapedPath` doesn't return the proper path with the "/" encoded as "%2F" and the URL sent on the request is incorrect. 

I wanted to get some feedback before submitting a PR. I think we can add something like
```
if req.URL.RawPath != "" {
        req.URL.RawPath = strings.Join(r.BasePath, req.URL.RawPath)
}
```
and do this for the reinstateSlash part following it as well. 
Alternatively, we can have basepath passed in to `buildHTTP` so that the URL is properly formatted on Parse and we don't have to twiddle with it afterwards. Would that break any compatibility if the signature changes?

Lastly, should the runtime call url.PathEscape on each of the pathParams before replacing them in the path or leave that up to the caller?

**Comment by casualjim** [comment]
buildHTTP is safe to change, it's not exported and if I understand you correctly that's the approach you prefer?

> Lastly, should the runtime call url.PathEscape on each of the pathParams before replacing them in the path or leave that up to the caller?
Yeah the runtime should call the path escape

**Comment by e-zhang** [comment]
Yeah, I think twiddling with the path prior to `url.Parse` seems like the safe way to go given the idiosyncrasies in the `net/url` package regarding paths. 

I'll take a look at making this change hopefully soon.
