### ISSUE TITLE
Meet error when get the latest version

### ISSUE THREAD

**Issue by yangliCypressTest** [go-openapi/runtime#86]
As the title.
The error messages is:
go-openapi/runtime/client/request.go:101: undefined: url.PathEscape
go-openapi/runtime/client/request.go:202: req.GetBody undefined (type *http.Request has no field or method GetBody)

**Comment by casualjim** [comment]
which go version?

**Comment by yangliCypressTest** [comment]
1.7.5

**Comment by casualjim** [comment]
can you update the runtime in your vendor or gopath
and update to go 1.8+

**Comment by yangliCypressTest** [comment]
yes, it is caused by the  golang version, thx for help.
