### ISSUE TITLE
location of binary releases

### ISSUE THREAD

**Issue by haroldcarr** [go-openapi/runtime#9]
the old repo:

https://github.com/go-swagger/go-swagger/releases/tag/0.5.0

had prebuild binaries

QUESTION 1: Is there anything like this now?

QUESTION 2: What is the relationship between the go-swagger repo and the go-openapi repo?

QUESTION 3: How does one build and executable (either everything, or just the validator)?

QUESTION 4: How does one test the executable?

**Comment by casualjim** [comment]
this is a supporting library but the the releases etc will still be through go-swagger/go-swagger/releases

I decomposed the github.com/go-swagger/go-swagger repository into several smaller ones so other people could build stuff on top of go-swagger without having to vendog github.com/go-swagger/go-swagger directly.

This repo kind of ties most of the other ones together and is used as runtime for the generated code etc.

The swagger command will still be in the other repo. Maybe for the openapi v3 spec I'll move it to this organisation.

**Comment by haroldcarr** [comment]
Thanks for the response.   I think I understand what you are saying to be answers to QUESTIONS 1 and 2.  

If one want to build the system, which repo should be cloned and what command issued from what directory?

**Comment by casualjim** [comment]
if you want to install HEAD for go-swagger.
```
go get -u github.com/go-swagger/go-swagger/cmd/swagger
```

if you want to run tests you can just use go test for the checkout of that repo.

**Comment by haroldcarr** [comment]
Thanks.  I apologize for the continued "dump" questions (I have never used go the language nor the ecosystem).  I get:

    package github.com/go-swagger/go-swagger/cmd/swagger: cannot download, $GOPATH not set. For more details see: go help gopath

**Comment by casualjim** [comment]
ah ok, and you want to use the binaries from master and not the ones from the 0.5 release?

**Comment by haroldcarr** [comment]
Correct.  All I really need is a binary of validation - but whatever path gets me to build a "master" that includes validation is what I am interested in.

**Comment by haroldcarr** [comment]
Now that I understand the relationship between the go-openapi repo and the go-swagger repo I understand that the instructions in the go-swagger repo (which you pointed out above):

    go get -u github.com/go-swagger/go-swagger/cmd/swagger

are what I need, first setting:

    export GOPATH=<where ever I want the resulting `bin`, `pkg`, `src` directories created

DONE.

One last QUESTION:  How often are the go-swagger and go-openapi repos synced?

**Comment by casualjim** [comment]
they are synced quite often. I try to update go-swaggers vendor whenever I merge a PR in any of the go-openapi repos

**Comment by haroldcarr** [comment]
Thanks for your help and the great system!
