### ISSUE TITLE
Enhancement: specify TLS CA certificate without file

### ISSUE THREAD

**Issue by dmjones500** [go-openapi/runtime#92]
In a similar vein to #90, I will be submitting a PR to add support for reading the `TLSClientOptions` CA certificate from memory, rather than a file.

E.g.

```go
type TLSClientOptions struct {
        // ...
	CA string
	LoadedCA *x509.Certificate
        // ...
}
```

The `Loaded` nomenclature feels ugly, but matches the route taken in #91.

We could make a breaking change to improve the terminology, as follows:

```go
// comments removed for brevity
type TLSClientOptions struct {
	CertificatePemFile string
	Certificate *x509.Certificate

	KeyPemFile string
	Key crypto.PrivateKey

	CAPemFile string
        CA *x509.Certificate // <--- the addition from this issue/PR

	ServerName         string
	InsecureSkipVerify bool
	_                  struct{}
}
```
It would also be nice to improve the logic so that the in-memory objects are used, when present, otherwise the files are loaded. Currently for the certificates and keys, either both are loaded from memory or both are loaded from disk.

I'll start work on a non-breaking change version of the above, but feedback here is very welcome on the idea of a more thorough refactoring.

**Comment by dmjones500** [comment]
Or we take it even further and just have the in-memory variants, leaving it as an exercise for the reader to load them from disk.

The feels like the Go approach (i.e. minimal), but clearly is a painfully breaking change.

**Comment by casualjim** [comment]
it would be nice if we could provide a non-breaking way of  providing this. It's unfortunate it can't be refactored cleanly but the gains of introducing a breaking change here are likely not that big that it justifies breaking the the public API

**Comment by dmjones500** [comment]
Ok, makes sense. In that case the PR is ready to go (#93).

**Comment by casualjim** [comment]
merged
